#!/bin/bash

set -e

WORKTREE_NAME="$1"
BASE_REF="$2"
WORKTREE_NAME_NORMALIZED="$3"

GIT_REPO="$(basename $(git remote get-url origin) .git)"

pushd "$WORKTREE_NAME"

# check for defaults from the codebase just checked out
if [ -e "runtime.txt" ]; then
    DEFAULT_PY_VERSION=$(cat runtime.txt | sed '/^#/d' | egrep -o "[0-9\.]+")
elif [ -e ".python-version" ]; then
    DEFAULT_PY_VERSION=$(cat .python-version)
fi

# define versions, venv name
PY_VERSION=${DEFAULT_PY_VERSION:-"3.10"}

echo "USING: python@$PY_VERSION"

uv venv --seed -p "$PY_VERSION"

source .venv/bin/activate

if [ -e "uv.lock" ]; then
    uv sync --dev
else
  uv pip install -r requirements.txt
  uv pip install -e .
fi
